### ISSUE TITLE
Check for duplicate before saving new alias

### ISSUE THREAD

**Issue by babolivier** [Nephylhim/gotoFonction#3]
I just added a new alias and realised afterwards I already had an alias for this exact path (even with the exact same name). The function should run a check before saving a new alias to check whether it's a duplicate of an existing alias.

**Comment by Nephylhim** [comment]
Thanks for your suggestion Babolivier ^^
I finally did it!

Last commit add this feature: https://github.com/Nephylhim/gotoFonction/commit/17073b3c1c32720a63f8ee00fa49e1e9b20402c5 #
